// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aemoflaphgavndkpylfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlbW9mbGFwaGdhdm5ka3B5bGZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMTYwMDMsImV4cCI6MjA3MjU5MjAwM30.Stwlz4JfFGtJoimzxM2o5VkHyVnoqbNwJPMAwcorQ68";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});